### ISSUE TITLE
small GUI fixes

### ISSUE THREAD

**Issue by marnixvb** [HuygensING/timbuctoo#149]
- [x] search interface: entities should be clickable
- [x] Timbuctoo-logo should link to upload gui (which is the 'home' of the user interface)
- [x] the link on the edit gui or the search gui should not open on a new tab
- [x] Rename 'download excel’ in search to ‘download csv' 
- [x] 'Search' should become 'Search all fields' 
- [x] unfocused search box should start searching (when enter pressed) 
- [x] Search interface should show the currently selected sort.
- [x] change text provenance, add disclaimer (@marnixvb need your input for actual disclaimer text)
- [x] upload and connect interface: rows are not aligned

**Comment by marnixvb** [comment]
@vmaccatrozzo could you change the text to:

<
Modified on {date} by {user}.

Timbuctoo documents full data provenance. 
Future releases will include a more detailed view of this provenance information.
>

So no header and the last to lines may differ in font from the first line (they function as disclaimer).
Thanks!

**Comment by vmaccatrozzo** [comment]
Look like this now, what do you think?

![screen shot 2017-02-21 at 16 22 47](https://cloud.githubusercontent.com/assets/5383705/23171161/0556414e-f852-11e6-9221-26090db00e59.png)

**Comment by marnixvb** [comment]
The header 'provenance' may be removed and if possible the two bottom lines may be in _italic_
Thanks!

**Comment by vmaccatrozzo** [comment]
Maybe the italic text should be also smaller in size??

![screen shot 2017-02-22 at 09 36 24](https://cloud.githubusercontent.com/assets/5383705/23203351/72d8be28-f8e2-11e6-8b22-1ab16a3fa982.png)

**Comment by marnixvb** [comment]
Yes, I think that would work. Thanks!
