### ISSUE TITLE
small GUI fixes (part II)

### ISSUE THREAD

**Issue by marnixvb** [HuygensING/timbuctoo#157]
**A list of textual changes to be made:**

- [x] overview: "Upload your first dataset" >> "Upload your data" 
- [x] overview: "Most university accounts will work." >> "Login required with the user account of your home institution"
- [x] overview: "Log in to upload" >> "Log in" 
- [x] "Create a new dataset" >> "Dataset information"
- [x] dataset settings: "To create e new dataset, please enter some basic information about your project" >> "Please enter some basic information about your data"
- [x] dataset settings: "Watch a 3 min [...]" >> weghalen zolang er nog geen video is [?]
- [x] maparchetypes: "Upload and connect your dataset" >> "Connect your data — Step 1"
- [x] maparchetypes: "Your excel sheet" >> "Your Excel sheet"
- [x] maparchetypes: "Connect to a Timbuctoo Archetype" >> "Specify type of data"

- [x] mapdata: "Upload and connect your dataset" >> "Connect your data — Step 2"
- [ ] mapdata: "Blad1 from [name].xlsx is connected to the Timbuctoo Archetypes. Map again"  >> "Blad1 from [name].xlsx contains data on [chosen archetype]. Change." 
- [x] mapdata: "Connect the excel columns to the properties of the Archetypes" >> "Please specify for all relevant columns the type of data they contain."
- [x] mapdata > Persons Archetype:
- "Persistent identifier" >> "Persistent identifier (e.g. VIAF or ISNI)" + can be moved after "Floruit"
- "Names" >> "Name"
- "Forename" >> "Given name(s) or initial(s)"
- "Surname" >> "Family name(s)"
- "Name link" >>"Family name prefix(es) (e.g. ‘de’, ‘van der’, certain noble titles)"
- "Gen name" >> "Name suffix(es) (e.g. ‘jr.’, ‘sr.’, ‘PhD’)"
- "Role name" >> "Name prefix(es) (e.g. ‘dr.’, ‘prof.’, royal and certain noble titles)"
- add: "Patronym"
- add: "Pseudonym"
- "Types": what does this field mean?
- "Birth date" >> "Date of birth"
- "Death date" >> "Date of death"
- "Floruit" >> "Floruit (i.e. time period in which person was active)"
- "Links": what does this field mean?
- "Add new property" >> "Define new" + separate from rest of text
&nbsp;&nbsp;&nbsp;&nbsp;- "Text" >> "Text format"
&nbsp;&nbsp;&nbsp;&nbsp;- "Datable" >> "Date format"
&nbsp;&nbsp;&nbsp;&nbsp;- "Property name" >> "Enter name"
&nbsp;&nbsp;&nbsp;&nbsp;- "Add propery" >> "Add to types of data"

**Comment by vmaccatrozzo** [comment]
- Floruit, Types and Links are properties that come from the uploaded data, so we cannot fix the names or remove them.

- "Birth date" >> "Date of birth" / "Death date" >> "Date of death"  -> these labels are generated dynamically from the label we use internally to represent the data, I can change them with a patch, but they won't match in the other guis.

- "Add new property" >> "Define new" + separate from rest of text -> what do you mean by separate from rest of text? some space in between? an horizontal line?

**Comment by marnixvb** [comment]
- ok, if still needed we change this in the excel (I'll ask this to the datamanagers)

- not sure whether I understand; let's discuss this tomorrow

- a horizontal line would we nice, thnx!

**Comment by jauco** [comment]
The changes break the upload (the captions are apparently also used as the rdf-uri's)

**Comment by vmaccatrozzo** [comment]
Which changes break the upload?
