### ISSUE TITLE
Goeie upload dataset (met vlookup)

### ISSUE THREAD

**Issue by jauco** [HuygensING/timbuctoo#161]

**Comment by marnixvb** [comment]
[demoset_toogdag_CLARIAH.xlsx](https://github.com/HuygensING/timbuctoo/files/821112/demoset_toogdag_CLARIAH.xlsx)

**Comment by jauco** [comment]
[DEMO_demoset_toogdag_CLARIAH_VIAF_VlookupPrepped.xlsx](https://github.com/HuygensING/timbuctoo/files/833192/DEMO_demoset_toogdag_CLARIAH_VIAF_VlookupPrepped.xlsx)
