### ISSUE TITLE
Landing page broken

### ISSUE THREAD

**Issue by lhuygi** [HuygensING/timbuctoo#171]
#### Steps to Reproduce
 1. Start Timbuctoo with `./devtools/debugrun/debugrun.sh`
 2. Open `http://localhost:8080` in a web browser
 
#### Expected/Desired behaviour

Timbuctoo GUI.

#### Actual behaviour

Redirect to `http://example.com`.

#### Extra info

The log output as written to the screen:
```
- INFO   >     GET http://localhost:8080/ [nl.knaw.huygens.timbuctoo.logging.LoggingFilter]
- INFO   < 307 GET http://localhost:8080/ (0 bytes) (9 ms) [nl.knaw.huygens.timbuctoo.logging.LoggingFilter]
```

Probably caused by 44c9906780a623a66643579c828dea25dce47653.

**Comment by MMaas3** [comment]
This is expected behaviour. To run with a landing page use: `timbuctoo/devtools/run-with-services/run.sh`
