### ISSUE TITLE
Demo datasets show 404

### ISSUE THREAD

**Issue by lwieneke** [HuygensING/timbuctoo#175]
#### Steps to Reproduce
 1. Go to http://acc.repository.huygens.knaw.nl/static/upload/#/?_k=miftrg
 2. Click on any dataset 
 
#### Expected/Desired behaviour
Dataset should open

#### Actual behaviour
Dataset is not shown, instead a 404 error appears

#### Extra info

The log output as written to the screen:
```
HTTP ERROR 404

Problem accessing /static/upload/null. Reason:

    Not Found
Powered by Jetty://
```

**Comment by jauco** [comment]
Sorry for not replying sooner (I should put mail notification on github issues 😄 )

You are correct that the acc version of timbuctoo doesn't have a search GUI running. However you can check out the search gui on https://anansi.clariah.nl/search/?vreId=74ccc032adf8422d7ea92df96cd4783f0543db3b_Carolus_Clusius_and_his_entourage

**Comment by lwieneke** [comment]
Hi Jauco,

Thanks a lot for the follow-up and the link!

- Lars
