### ISSUE TITLE
Running timbuctoo from Docker

### ISSUE THREAD

**Issue by 4tikhonov** [HuygensING/timbuctoo#193]
#### Steps to Reproduce
I just tried to build docker image and it goes fine:
```docker build -t timbuctoo .```

#### Actual behaviour
After attempt to start docker container I'm getting error message that folder '/data' is missing:
```docker run -p 8080:8080 timbuctoo``` 

I think /data should be relative path with some dummy examples of user credentials and datasets.

#### Extra info

The log output as written to the screen:
```
- INFO   Logging initialized @2786ms to org.eclipse.jetty.util.log.Slf4jLog [org.eclipse.jetty.util.log]
- INFO   Registering jersey handler with root path prefix: / [io.dropwizard.server.DefaultServerFactory]
- INFO   Registering admin handler with root path prefix: / [io.dropwizard.server.DefaultServerFactory]
- INFO   Registering AssetBundle with name: assets for path /static/* [io.dropwizard.assets.AssetsBundle]
- INFO   Setting up activeMq with brokerUrl vm://timbuctoo?broker.persistent=false&broker.useShutdownHook=false [com.kjetland.dropwizard.activemq.ActiveMQBundle]
- ERROR  NO-GIT-PROPERTIES-FOUND [nl.knaw.huygens.timbuctoo.server.TimbuctooV4]
- INFO   Now launching timbuctoo version: NO-GIT-PROPERTIES-FOUND [nl.knaw.huygens.timbuctoo.server.TimbuctooV4]
- INFO   Using dummy persistence manager instead of real handle server [nl.knaw.huygens.timbuctoo.server.endpoints.v2.Gremlin]
File does not exist
- ERROR  File /data/auth/users.json does not exist [n.k.h.t.security.dataaccess.localfile.LocalfileAccessFactory]
```

**Comment by jauco** [comment]
You probably built timbuctoo before. It seems that the buildbase image is out of date. 

Do a `docker pull huygensing/timbuctoo:buildbase` to fix it. Or just run one of the prebuilt images from docker hub (huygensing/timbuctoo)
