### ISSUE TITLE
[T124] index NEWW VRE

### ISSUE THREAD

**Issue by marnixvb** [HuygensING/timbuctoo#254]

**Comment by MMaas3** [comment]
Het probleem is een corrupte database. Timbuctoo geeft twee keer de verkeerde Viitanen (http://resources.huygens.knaw.nl/womenwriters/vre/persons/4443aaac-76bc-4484-97ed-36a637957469) terug. De eerste keer is het de juiste versie. De tweede keer is het een oudere versie uit september 2017.

We kunnen het probleem fixen door een wijziging te doen in de graafdatabase. We kunnen ook Women Writers converteren naar rdf en hem verder laten werken met de nieuwe Timbuctoo.

**Comment by marnixvb** [comment]
Hoe schat je het werk (i.e. de uren) in voor beide oplossingen?

**Comment by MMaas3** [comment]
De graafdatabase fixen is een kwestie van uren.
De dataset omzetten een kwestie van dage.
