### ISSUE TITLE
T121: Importer heeft een bug. 

### ISSUE THREAD

**Issue by MMaas3** [HuygensING/timbuctoo#263]
Ik was twee datasets tegelijk aan het uploaden en paste toen de naam van de eerste dataset aan. Dan zie je twee imports lopen (van beide datasets 1) toen de tweede import klaar was ging de 2e log van de eerste dataset ook al importeren. Voordat de eerste log dus klaar was.

**Comment by jauco** [comment]
Steps to reproduce:

 - upload one datasets that takes awhile to finish
 - *before it's finished* execute a graphql mutation that generates a log
 - *before it's finished* upload a second dataset that finishes faster

What you should see: the mutation log on dataset 1 starts processing even though the initial import of dataset 1 hasn't finished yet.

What I expect to see: the mutation log should wait until the initial import is finished

**Comment by pjoshi04** [comment]
Closing this issue for now as I have been unable to reproduce the issues. If anyone encounters it again we can re-open the issues.

**Comment by marnixvb** [comment]
@pjoshi04 to try on Golden Agents production server

**Comment by MMaas3** [comment]
We reopen the issue if this happens again on production.
