### ISSUE TITLE
T140: Stardog-server Golden Agents: size limit

### ISSUE THREAD

**Issue by marnixvb** [HuygensING/timbuctoo#275]

**Comment by pjoshi04** [comment]
Discovered that the uploads work fine for the smaller files but the problem shows up even if you try to upload one of the larger files (3-4Gb/each) individually. Posted on the Stardog server forums and the answer received was to manually increase the memory as follows:

`STARDOG_SERVER_JAVA_ARGS="-Xms4g -Xmx4g -XX:MaxDirectMemorySize=8g"`

However, this did not work for us even with memory set upto 100gb. Stardog would get stuck in the 'computing statistics' portion no matter whether it was on default, 4g, 16g, 100g.

Do not have additional information from Stardog Support to procede further.

**Comment by pjoshi04** [comment]
As per the reasons described in the above comment and discussion with Jauco, we have decided to not move forward with Stardog.
