### ISSUE TITLE
T145 message on homepage NEWW VRE

### ISSUE THREAD

**Issue by marnixvb** [HuygensING/timbuctoo#278]

**Comment by MMaas3** [comment]
Jauco needs to find the user and password for the site, that will cost him an hour, that he cannot use for other Structured Data related projects. After this is done the project leader will be able to do this herself.

**Comment by marnixvb** [comment]
ok, I'll notify them on this; an hour is okay

**Comment by marnixvb** [comment]
deadline = Thursday 20
