### ISSUE TITLE
Harvest Women Writers

### ISSUE THREAD

**Issue by MMaas3** [HuygensING/timbuctoo#284]
vanuit een query [volgt nog] wordt een subset van de data in json opgehaald -- deze converteren naar RDF; afhankelijk van hoeveelheid werk kijken in hoeverre specifiek gemapt dient te worden

**Comment by MKroese** [comment]
Mutatie-file (mutaties.txt) opgeslagen op onze surfdrive (Team red/ codlprobleem)

**Comment by marnixvb** [comment]
http://resources.huygens.knaw.nl/womenwriters/vre/documents#q=%7B%22authors%22%3A%7B%22searchFields%22%3A%5B%7B%22label%22%3A%22Country%22%2C%22field%22%3A%22relatedLocations_ss%22%2C%22type%22%3A%22list-facet%22%2C%22collapse%22%3Afalse%2C%22value%22%3A%5B%22Netherlands%22%5D%7D%2C%7B%22label%22%3A%22Language%22%2C%22field%22%3A%22language_ss%22%2C%22type%22%3A%22list-facet%22%2C%22collapse%22%3Afalse%2C%22value%22%3A%5B%22Dutch%22%5D%7D%5D%2C%22sortFields%22%3A%5B%5D%7D%2C%22publications%22%3A%7B%22searchFields%22%3A%5B%5D%2C%22sortFields%22%3A%5B%5D%7D%2C%22authorReceptions%22%3A%7B%22searchFields%22%3A%5B%5D%2C%22sortFields%22%3A%5B%5D%7D%2C%22publicationReceptions%22%3A%7B%22searchFields%22%3A%5B%5D%2C%22sortFields%22%3A%5B%5D%7D%7D​
