### ISSUE TITLE
Add create / delete mutation

### ISSUE THREAD

**Issue by MMaas3** [HuygensING/timbuctoo#293]
design: https://github.com/HuygensING/timbuctoo/blob/master/documentation/design/edit-mutations.adoc

Customizing the dynamic schema: https://github.com/HuygensING/timbuctoo/blob/master/timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/graphql/README.adoc#customizing-the-dynamic-schema

**Comment by marnixvb** [comment]
To be released
