### ISSUE TITLE
After deleting a dataset, the dataset sticks around in the list with datasets (but the graphql errors out because the dataset is closed)

### ISSUE THREAD

**Issue by jauco** [HuygensING/timbuctoo#313]
#### Steps to Reproduce

Try to do so on the golden agents server (not this week though)
 1. create a dataset
 2. delete it (maybe during an upload?, maybe you need to publish it first?)
 
#### Expected/Desired behaviour
The frontpage should show all datasets

#### Actual behaviour
The front page shows an error that the dataset is closed

**Comment by MMaas3** [comment]
The GraphQL schema will nog crash anymore since pull request #322
