### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by hayco** [HuygensING/timbuctoo#342]
#### Steps to Reproduce
 1. Go to https://github.com/HuygensING/timbuctoo#querying-data-and-applying-mutations
 2. Click the link in "You can then refer to [this Timbuctoo GraphQL API guide] for querying and mutation instructions with examples."
 
#### Expected/Desired behaviour
The link works and shows the "Timbuctoo GraphQL API guide"

#### Actual behaviour
The link ends up at a 404 booboo.

#### Extra info

The log output as written to the screen:
```
Not Found
```

**Comment by hayco** [comment]
MMaas once said: be sure to 'assign someone' so we notice the issue. Hence 'kerim1' assignment. Feel free to re-assign.

**Comment by kerim1** [comment]
Are you using the Docker image? I just ran a new Timbuctoo container and the link http://localhost:8080/static/graphiql shows me the expected result. Actually http://localhost:8080 should just redirect to the GraphiQL interface right away.

**Comment by hayco** [comment]
Please read my "Steps to reproduce" and follow those. My report is about the documentation as it is available on Github. I am not at all suggesting this is from an actual install.
