### ISSUE TITLE
software metadata: bogus version number in pom.xml?

### ISSUE THREAD

**Issue by proycon** [HuygensING/timbuctoo#357]
The CLARIAH tool discovery harvester is a bit thrown off by the 'bogus version number' in your [pom.xml](https://github.com/HuygensING/timbuctoo/blob/master/pom.xml#L7), it now harvests and reports this bogus version in the index: https://tools.dev.clariah.nl/timbuctoo .

It would be ideal if you can put a non-bogus version there or to just leave it out altogether  (but I guess pom.xml doesn't allow that).
If you really have to keep a bogus number there, please add a `codemeta-harvest.json` with the correct version number, as per https://github.com/CLARIAH/clariah-plus/blob/main/requirements/software-metadata-requirements.md .

**Comment by kerim1** [comment]
We were finally able to restructure the whole codebase. The pom.xml now has an actual version number. And looking at https://tools.dev.clariah.nl/timbuctoo it seems the harvester picks up the right version number now.
